### PR TITLE
Liquefaction added

### PR DESCRIPTION
**Pull request by anna-nadia**
Added liquefaction (and evaporation) functionality via a new H2 liquid balance expression
Updated TDR to process new liquid demand input file
Updated result files, including adding new elec costs file (variable electricity costs associated with H2 production)
Updated trucking module to distinguish between gas and liquid trucks (LOHC not included) and to filter routes on user-specified distance -> settings parameter added in the hsc_settings file. 
Example system with 3 zones added that includes liquefaction

### CODE REVIEW

**Review by Betristor — DISMISSED** [review]

**Review by Betristor — DISMISSED** [review]

**Comment by anna-nadia** [comment]
@dharik13 @RuaridhMacd I have updated the documentation to reflect liquefaction changes. I think this branch should be good to merge now.

**Comment by RuaridhMacd** [comment]
- [ ] @shakesy94 Review the model logic of the documentation

@dharik13

**Comment by RuaridhMacd** [comment]
- [ ] @anna-nadia @dharik13 Add diagram of the H2 balance from your paper

**Comment by shakesy94** [comment]
The logic of the modelling looks good to me. I have 2 comments: 1) I see conflicts with the main branch. These should be resolved. 2) @anna-nadia did you try running the model with liquefaction turned off to see if it runs fully without issue + if the results for an existing model would turn out the the same?

**Comment by RuaridhMacd** [comment]
- [ ] @shakesy94 Run liquefaction tests in next few days
- [ ] @shakesy94 Write-up / submit review
- [ ] @dharik13 Review merge conflicts

**Comment by anna-nadia** [comment]
Hi Youssef, yes the model runs without liquefaction as well. I have a
scenario where I run with gaseous demand only. Thanks for reviewing the
code!

**Comment by dharik13** [comment]
I pushed a commit to Liquefaction balance  branch where I made changes to allow the model to run without errors when ModelH2Liquid =0 or not specified (in which case, configure_settings file adds a default value of ModelH2Liquid = 0 along with default value of missing parameters). 

Youssef and Anna, please check and approve when you get a chance.

**Comment by shakesy94** [comment]
Apart from the two comments I have added, this looks good to me. I ran the test case and ispected the results as well. @dharik13 @anna-nadia  if you can respond to those comments, I will be ready to approve.

**Comment by RuaridhMacd** [comment]
- [ ] @RuaridhMacd Re-test with resolved conflicts

**Comment by shakesy94** [comment]
If you go to the files changed tab, and navigate to the load_h2_gen.jl, load_h2_truck.jl, h2_production.jl files. On there you will be able to see my comments.

**Comment by dharik13** [comment]
@shakesy94 please review updated liquefaction balance branch and then approve so that we can merge with main.

**Comment by shakesy94** [comment]
I resolved some conflicts with main, but Github is still asking for a review and is not giving me the option to provide it. I think it may be because I made the latest changes. @dharik13 @RuaridhMacd  can either of you try approving it?

**Review by shakesy94 — APPROVED** [review]

**Pull request merged**
