### PR TITLE
update copyrights

### PR DESCRIPTION
**Pull request by Betristor**
Update copyrights
1. change year to 2022
2. change network to nexus
3. add Peking University
4. drop unnecessary white space

### CODE REVIEW

**Comment by RuaridhMacd** [comment]
Hi @Betristor,
I checked here and we're meant to leave the license as it is, including "Networks" in the name, so I'm going to close this PR.

**Comment by Betristor** [comment]
OK, anyway it's easy to change copyrights with vscode using find and replacement. I'll delete the branch.

**Comment by dharik13** [comment]
Hi @Betristor , please note that the license cannot be modified per MIT open-source release terms. I would only change the year on the license to 2022 wherever it is not that already - @RuaridhMacd can you take care of this.

**Comment by RuaridhMacd** [comment]
@dharik13 @Betristor Yes, I can update them

**Comment by Betristor** [comment]
@RuaridhMacd Hi, Mac, the white space in the license declaration is not added by mistake? Sorry I didn't notice that. I thought it shouldn't be there.

**Comment by RuaridhMacd** [comment]
@Betristor It's a style choice which is common in legal documents to improve readability, but one or two spaces are both correct.

**Pull request closed without merging**
