### PR TITLE
Track power balance using expressions

### PR DESCRIPTION
**Pull request by Betristor**
In power sector, power balance plays the most important role in establishing the model and its composition will be more and more complicated if we keep adding more terms, which will definitely cause problem when writing power balance in results.

1. Add transmission term
2. Add demand term - inputs demand minus non served demand + additional demand from other sectors
3. Add additional demand
4. Write these terms in writing balance function

P.S. Hydrogen sector is not handled so additional demand is not processed. By the way expression eH2NetpowerConsumptionByAll could be used as part of additional demand but term additional demand could be extended if more sectors are to be added.

### CODE REVIEW

**Comment by dharik13** [comment]
Revise the PR to populate eAdditionalDemandbyZone expression with power consumption by H2 supply chain.

**Comment by Betristor** [comment]
@RuaridhMacd ```eAdditionalDemandbyZone``` contains power demand from other sectors like hydrogen and carbon. With  ```eH2NetpowerConsumptionByAll``` expression, the additional demand from power could be accessed easily. But as for the index sequence, I think we should have a consistent way to arrange how to index the data, especially with basic dimension of spatial and temporal. I'd like to use zone and time indexed as z,t. This way is more readable.
Similar expressions in hydrogen sector is also added.

**Comment by RuaridhMacd** [comment]
- [ ] For now leave at [t,z] to stay consistent with the rest of the codebase
- [ ] @RuaridhMacd Make a proposal for consistent outputs

**Comment by Betristor** [comment]
@RuaridhMacd There exist some codes with index sequence of zone and time (z,t) in genx we used in main branch such as ```eGenerationByZone```, ```eGenerationByVRE```, ```eGenerationByHydroRes``` and expressions in transmission like ```eNet_Export_Flows``` and ```eLosses_By_Zone```. I will leave these code aside and focus on the code I added.

**Comment by RuaridhMacd** [comment]
@Betristor This looks good. I think it's fine to leave the other existing (z,t) cases for now, to avoid causing issues.

Are you ready for me to review and merge this?

**Comment by Betristor** [comment]
@RuaridhMacd These expressions won't affect any codes in establishing the model but just track some numbers we want to know. As a start, I hope with the model scope expanding, these expressions could help record any detailed while small terms as a whole and save the trouble in writing output part.

I added a term in write_h2_balance.jl named transmission. Now it's ready to go.

**Comment by RuaridhMacd** [comment]
- [ ] @RuaridhMacd Ask Justin to experiment with [t,z] creating and writing formulations

**Review by RuaridhMacd — APPROVED** [review]
The changes worked for me on the three example systems and the additional expressions were written correctly.

@Betristor , merge this if you're happy to proceed.

**Comment by Betristor** [comment]
@RuaridhMacd I merged the PR.

**Pull request merged**
