### PR TITLE
202 hsc units mass to energy

### LINKED ISSUE #202: [Feature]: Convert HSC units from mass-based units (e.g. tonne H2) to energy-based units (MWh based on HHV of H2)
### What new feature do you propose?

[WIP]

It will be advantageous for Dolphyn to manage H2 resources and demand in units of energy rather than mass. Let's convert all the mass units to energy units based on the higher heat value of H2.

- [ ] Change input handling
- [ ] Change output writing
- [ ] Change internal logic for energy conversions

### Please link any issues this feature would resolve

_No response_

### What suggestions do you have for implementing this feature?

Tell us your way to implement this feature. Any suggestions?

### Please add any relevant labels using the drop-down menu on the right.

- [ ] I have added all relevant labels.

### PR DESCRIPTION
**Pull request by bennettm**
# Description

This pull request is for converting HSC from mass (tonne) to energy (MW).  Such conversions is throughout the codes in julia files from HSC folder as well as related documentations (.md files).  Input data in CSV files have been converted with column names to express energy (MW) instead of mass (tonne) and the respective values have been converted using HHV (39.38). Some columns do not use tonne but the value is in mass so they got converted nevertheless.  Below provided the link to the wiki file that have column name changes from "tonne" to "MWh" and those columns that don't contain "tonne" but their values should be converted are recorded in the second attached document below titled "column_no_tonne.docsx".   

[tonne_to_mw_csv_data](https://github.com/macroenergy/Dolphyn.jl/wiki/CSV-Input-Data-File-Column-Name-Change-from-Mass-%28tonne%29-to-Energy-%28MWh%29)
[no_tonne_columns.docx](https://github.com/macroenergy/Dolphyn.jl/files/13788853/no_tonne_columns.docx)

Examples cases with input and results dataare shared through sharepoint [here](https://mitprod-my.sharepoint.com/:f:/g/personal/mbennett_mit_edu/EjhyLc1d89JPhEdBhO1du5MBGjyPddY_MCFRS4PxNzmy3w?e=yK8uuF).

This input data file HSC_CO2_cap.csv did not have to have its values updated from mass to energy because currently the values are all in zeros.  The setting for using this file is h2CO2Cap in hsc_setting.yml.  The examples that use this file is: 

- Eastern_US_CSC/ThreeZones
- NorthSea_2030
- NorthSea_2040_SF_Examples

## Fixes issue \#

This is a feature from #202. 
Through the work, some minor bugs are discovered and in order to get a better results, these minor bugs will get fixed through this PR. These bugs include: 1. use flag in settings file instead of checking the existence of HSC_g2p.csv. 2. NorthSea_2030 overwrites Results folder each time instead of creates a new results folder. 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
I have run all following example cases. I have used HiGHS solver to do all testings.  The table, below, provides the difference between objective value in mass unit versus objective value in energy for each example case. 

|Example Name|OV in mass|OV in energy|
|---------|------|-------|
|SNE-OneZone| 9.42|9.42|
|SNE-ThreeZones|4.80|4.80|
|SNE-ThreeZones_Liquid|7.05|7.03|
|Eastern_US_CSC/ThreeZones| 9.09| 9.09
|NorthSea_2030|5.88|5.77|
|NorthSea_2040_SF_Examples|2.21|2.22

Since "NorthSea_2030" objective value results between mass and energy show major differences, a more step by step testing was carried out to sort out.   Setting flags (from hsc_settings.yml) are turned on step by step.  Here is the outcome:

|                 |OV in mass | OV in energy|
|----------|------------|-------------|
|ModelH2 on only|5.89|5.91|
|ModelH2+NWExpansion|5.87|5.89|
|ModelH2+NWE+ CO2Cap|5.79|5.91|
|ModelH2+NWE-CO2Cap+Pipelines|5.76|5.75|
|ModelH2+NWE-CO2Cap+Pipelines+G2P|5.77|5.66|

Testing has been done using Gurobi. Here is the results for six example cases corresponding to the above-listed six example cases with HiGHS:

|            | OV in mass | OV in energy|
|-------|-------------|-------------|
| SNEOneZone| 9.42| 9.42|
| SNEThreeZones| 4.80 | 4.80|
| SNEThreeZones_Liquid| 7.06 | 7.05|
| Eastern_US_CSC| 9.09  |9.09|
| NorthSea_2030-co2cap-off|5.92  | 5.92|
| NorthSea_2030-co2cap-on|5.90 | 5.90|
| NorthSea_2040| 2.22 | 2.21|

The following provides  the logs for NorthSea_2030 testing results with Gurobi from mass-based and energy-based respectively with CO2cap option on and off:

|         |  mass-based | energy-based|
|------| ---------|--------------|
|CO2cap:0 |  [mass-based-no-co2cap.txt](https://github.com/macroenergy/Dolphyn.jl/files/15042144/mass-based-no-co2cap.txt)   |  [energy-based-no-co2cap.txt](https://github.com/macroenergy/Dolphyn.jl/files/15042148/energy-based-no-co2cap.txt) |
|CO2cap:1 | [mass-based-co2cap-on.txt](https://github.com/macroenergy/Dolphyn.jl/files/15042186/mass-based-co2cap-on.txt)   | [energy-based-co2cap-on.txt](https://github.com/macroenergy/Dolphyn.jl/files/15042188/energy-based-co2cap-on.txt) |

Tests have run successfully except  "ERCOT_1stg_hourly_5GW_base_tmr". It gives the error:

```ERROR: LoadError: MethodError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer```

- [x] Example_Systems/SmallNewEngland/OneZone 
- [x] Example_Systems/SmallNewEngland/ThreeZones
- [x] Example_Systems/SmallNewEngland/ThreeZones-Liquid
- [x] Example_Systems/ERCOT_1stg_hourly_5GW_base_tmr
- [x] Example_Systems/Eastern_US_CSC/ThreeZones
- [x] Example_Systems/NorthSea_2030
- [x] Example_Systems/NorthSea_2040_SF_Examples

**Test Configuration**:
* OS:  Mac
* Solver: Highs
* Julia version: 1.9
* Solver version:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [] I have run tests with my code to avoid compatibility issues
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by bennettm** [comment]
@RuaridhMacd column name change for input data is in a wiki page whose link is provided in the above pull request description, result data is completed for all examples and shared examples folders are all set.  This pull request is good for review.  Let me know who I should share the example folders with.

**Comment by Junwenlaw** [comment]
Reason that Eastern_US_CSC does not match is because synthetic fuels also have hydrogen inputs and they are in terms of tonne H2/tonne CO2 in the file of Syn_Fuels_resources.csv column tonnes_h2_p_tonne_co2. So that have to be changed into energy terms.

**Comment by Junwenlaw** [comment]
Similar to North Sea SF that has synthetic fuels. The reason is H2 units in the synfuels inputs are in tonnes, but the system is already running in MW terms.

**Review by RuaridhMacd — APPROVED** [review]
This works for me and the tests produce the same results. We still need to upload a script to convert other examples from tonnes -> energy

**Comment by RuaridhMacd** [comment]
Resolved in #253

**Pull request closed without merging**
