### PR TITLE
Fix examples

### PR DESCRIPTION
**Pull request by Betristor**
Existing examples in main branch are broken after several PRs are merged. Different schedule and untimely development caused this situation.
The most annoying problem lies in the unstructed inputs part. In TDR part and later data loading part, it's quite messy to understand the desired inputs structure.
I should first to transfer the inputs to be more compatiable with the loading structure merged before in truck module development. And then test and merge branch [base_model](https://github.com/macroenergy/DOLPHYN/tree/base_model) to make the inputs and outputs structure more clean.

### CODE REVIEW

**Comment by Betristor** [comment]
Intended examples
- [ ] OneZone example in SmallNewEngland
- [ ] ThreeZones example in SmallNewEngland
- [ ] ThreeZones_liquid example in SmallNewEngland
- [ ] Select_Zone example (added when zone pickup feature was introduced)

**Comment by Betristor** [comment]
Intended examples
- [ ] OneZone example in SmallNewEngland
- [ ] ThreeZones example in SmallNewEngland
- [ ] ThreeZones_liquid example in SmallNewEngland
- [ ] Select_Zone example (added when zone pickup feature was introduced)

**Comment by Betristor** [comment]
@RuaridhMacd Mac, I rebased this branch to your genx_as_submodule and tried to fix the examples we used in DOLPHYN. I managed to have **2030_CombEC_DETrans**, **OneZone**, **ThreeZones**, **ThreeZones_Liquid** and **TenZones** to build the model when operation mode is off. But this option originated from GenX is not quite compatiable with our code. In **Select_Zone** case, the zone selection is only functionable in HSC sector while GenX keeps its own way of dealing with data, so it does not affect the data structure there. Temporally this feature is partially useful. And I may close this PR and create one to your genx_as_submodule. Or I could wait for you merged that branch and then merge this.

**Comment by RuaridhMacd** [comment]
- [ ] Review new examples with the genx_as_submodule branch

**Pull request closed without merging**
