### PR TITLE
Select zone from inputs

### PR DESCRIPTION
**Pull request by Betristor**
Previously we need to create another folder with data to select zone and then create such scenario. With zone selection feature, we could control such behavior in global_model_settings file.

1. Add zone selection in power inputs selection
2. Add zone selection in hydrogen inputs selection
3. Create pipe map and line map in hydrogen pipeline inputs and power inputs using start zone and end zone instaed of matrix

### CODE REVIEW

**Comment by Betristor** [comment]
Pipe map still will have type error if we input zone list in global settings using strings, cause in model part (file h2_pipeline.jl) we need to use Zone column in pipe map to match pipeline flow term. We should discuss how to design this input term and guide user to do like this. Using strings to represent zones is more comfortable for users cause this's meanful.

**Comment by RuaridhMacd** [comment]
Hi @Betristor, these look like good additions. I will have time to test them properly on Thursday, so will do the review for this and issue #117 then.

**Comment by Betristor** [comment]
This branch selects specific zones from ```global_model_settings.yml``` file with entry ```Zones``` to denote which zones to be modeled. And all zone column should be consistent. Temporarily using string for zones as identifier is tested and verified. Using strings is more readable for users, so I recommend to denote zones with strings.

**Comment by Betristor** [comment]
@RuaridhMacd Breaking changes include 1. choose zones set from settings (list of string); 2. use start zone and end zone to denote a transmission line or pipeline. This branch doesn't contain modifications in truck route so this should be handled before truck revision.

**Comment by RuaridhMacd** [comment]
- [ ] Test discontinuous groups of zones, e.g. Zones = [1,3]
- [ ] Make Zones optional, so not including it in global_settings defaults to using Zones = all zones
- [ ] Add warning (@warn) / error() if Zones are not listed sequentially

**Comment by Betristor** [comment]
@RuaridhMacd I tested a continuous case with Zones = ["z1", "z3"], it worked out. 
Then I tested a case with Zones = ["z2", "z1"]. The results are correct in number but wrong in sequence. We need to change the column name when writing outputs to make them match with Zones in global settings. Considering the user experience when zones are selected, I prefer to use strings and use the same list when writing output. So the third task seems not perfect for the code development.
So, instead of add warning for unsequenced input list, I change the correspondence in the writing output part.

**Comment by Betristor** [comment]
@RuaridhMacd As for the second task, I think based on the current code development, it will cost more convenience to set a default action when zones list is left none. Here are my thoughts and reasons.
1. Zones are almost surely known to users when a new case is established;
2. Network and pipeline routes as well as truck routes are to be decided by merely a pair of start zone and end zone to save input trouble for users so that all zones are included in either network.csv or pipelines.csv is not ensured;

But there do exist some other cases where zone set is pretty large and many zones should be included like hundred of zones need to be listed, quite annoying for users, making a "select all" option welcome. But still the zone set need to be known by the model. Previously we construct a matrix containg all zones and is sparse. It's useful when zone set is small, while inconvenient under the assumption that zone set is large. 

Regarding all these, I think a "select all" option will be a new feature we need but I may not implement now. (Honestly, I have not come up with a good way to store and access zone list to be compatible with the way Genx took and the way I adopted to construct the spatial matrix.)

**Comment by RuaridhMacd** [comment]
Hi @Betristor 
Thanks for working through these so quickly.

That looks good for tasks 1 and 3. I'm happy to use strings for the zone names.

It looks like we have more work to do on task 2. I like the idea of having a default action which selects all zones because it avoids issues for users with existing simulations. 
Integrating this zone-select feature with GenX will also be tricky if we're moving to using the GenX submodule. Perhaps we should have a discussion / issue with the others working on GenX to hear their opinion on how to implement it.

**Comment by Betristor** [comment]
@RuaridhMacd Yeah, I. agree with that. I think the main idea we need to discuss is how to design spatial matrix inputs for transmission lines in Genx, pipeline map and truck routes for hydrogen. Based on a widely accepted way of input, we could find out some way to implement zone selection feature with a default action.

Temporarily, I could access zone list from the inputs as a pre-check to save users' trouble when zone list is left none, which means select all zones from the inputs. To filter zones when loading inputs is not only helpful when a subset of zones is needed, but also we could use it as some kind of checks to ensure users' inputs are in match in spatial aspect.

**Comment by RuaridhMacd** [comment]
- [ ] @Betristor Add basic default behavior to create a Zone list based on the network_data.csv input, if the Zone : [...] setting is missing

**Comment by Betristor** [comment]
@RuaridhMacd Mac, I enumerated all zones from power transmission lines and hydrogen pipelines to include all zones if no zones entry is provided (no zones entry or empty list). The function is implemented in ```enumerate_zones.jl```.

**Comment by RuaridhMacd** [comment]
- [ ] @RuaridhMacd Review this week

**Review by Betristor — COMMENTED** [review]
@RuaridhMacd I've reviewed all changes from main, the modifications won't affect existing code. And as the author of this PR, I can't approve it, but I think it's ready to go.

**Comment by RuaridhMacd** [comment]
Thanks @Betristor . I've just merged it.

**Pull request merged**
