### PR TITLE
Auto test using github actions

### PR DESCRIPTION
**Pull request by Betristor**
1. Change solver from gurobi to highs
2. Configure highs options to be compatiable with HiGHs.jl
3. Compare results with example we provided
4. Add github action workflow

### CODE REVIEW

**Comment by Betristor** [comment]
@RuaridhMacd Automatic test using github actions on one-zone case is done, other cases could be appended after one zone test script. I cached julia project for reusage using julia-actions/cache and tried to compare results with example folders. Now the only problem is how to notify users when summary.txt is created.

**Comment by RuaridhMacd** [comment]
@Betristor This is great! I hadn't realized installing HiGHS.jl also installs the HiGHS binary. That makes it much easier.

Let me know if you'd like to discuss how to compare results, but I think a simple table which compares the "Total" columns of costs.csv and hsc_costs.csv would be a good start.

**Review by RuaridhMacd — CHANGES_REQUESTED** [review]
All of the SmallNewEngland examples work for me locally. The NorthSea example also works but is much slower with HiGHS than with Gurobi.

I'd recommend that we also run ThreeZones_Liquid, as that tests some of the features missing from the OneZone case.

**Comment by Betristor** [comment]
> @Betristor This is great! I hadn't realized installing HiGHS.jl also installs the HiGHS binary. That makes it much easier.
> 
> Let me know if you'd like to discuss how to compare results, but I think a simple table which compares the "Total" columns of costs.csv and hsc_costs.csv would be a good start.

@RuaridhMacd I found there is no need to install highs binary on github ubuntu machine to perform the tests. And I added other example case to be tested. 
Considering how to check whether results are in match with previous version. Your script ```compare_results``` is a good starting point.
Besides I added conditions to allow test bypassing since there exists some situations when we don't want the test to be triggered. When specified keywords are included in the commit message, then the test could be skipped.

**Pull request closed without merging**
